// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"
	attestation "slsa-verde/internal/attestation"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// Verifier is an autogenerated mock type for the Verifier type
type Verifier struct {
	mock.Mock
}

// Verify provides a mock function with given fields: ctx, container
func (_m *Verifier) Verify(ctx context.Context, container v1.Container) (*attestation.ImageMetadata, error) {
	ret := _m.Called(ctx, container)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *attestation.ImageMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.Container) (*attestation.ImageMetadata, error)); ok {
		return rf(ctx, container)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.Container) *attestation.ImageMetadata); ok {
		r0 = rf(ctx, container)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*attestation.ImageMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.Container) error); ok {
		r1 = rf(ctx, container)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVerifier creates a new instance of Verifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Verifier {
	mock := &Verifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
