apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slsa-verde.fullname" . }}
  labels:
    {{- include "slsa-verde.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "slsa-verde.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slsa-verde.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "slsa-verde.name" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            {{ if .Values.config.useServiceAccountKey }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secrets/google/key.json
            {{ end }}
            - name: DOCKER_CONFIG
              value: /etc/docker-credentials
            {{- if .Values.webproxy.enabled }}
            - name: HTTP_PROXY
              value: http://webproxy.nais:8088
            - name: http_proxy
              value: http://webproxy.nais:8088
            - name: HTTPS_PROXY
              value: http://webproxy.nais:8088
            - name: https_proxy
              value: http://webproxy.nais:8088
            - name: NO_PROXY
              value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io,.aivencloud.com,.intern.dev.nav.no,{{ .Values.webproxy.additionalNoProxy }}
            - name: no_proxy
              value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io,.aivencloud.com,.intern.dev.nav.no,{{ .Values.webproxy.additionalNoProxy }}
              {{- end }}
            - name: VULNERABILITIES_API_URL
              value: {{ .Values.config.vulnerabilitiesGrpcUrl }}
            - name: SERVICE_ACCOUNT_EMAIL
              value: {{ .Values.config.serviceAccountEmail }}
            - name: CLUSTER
              value: {{ .Values.config.cluster }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel }}
            - name: INFORMER_RE_LIST_HOURS
              value: {{ .Values.config.informerReListHours | quote }}
            - name: GITHUB_ORGANIZATIONS
              value: {{ .Values.config.github.organizations }}
            - name: DEPENDENCYTRACK_TEAM
              value: {{ .Values.config.dependencytrack.team }}
            - name: DEPENDENCYTRACK_API
              value: {{ .Values.config.dependencytrack.api }}
            - name: DEPENDENCYTRACK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "slsa-verde.fullname" . }}
                  key: dependencytrack_username
            - name: DEPENDENCYTRACK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "slsa-verde.fullname" . }}
                  key: dependencytrack_password
            - name: COSIGN_KEY_REF
              valueFrom:
                secretKeyRef:
                  name: {{ include "slsa-verde.fullname" . }}
                  key: cosign_key_ref

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            {{ if .Values.config.useServiceAccountKey }}
            - mountPath: /var/run/secrets/google
              name: google-service-account
            {{ end }}
            - mountPath: /etc/cosign
              name: config-volume
            - mountPath: "/etc/slsa-verde"
              name: slsa-verde-config
            - mountPath: /.sigstore
              name: writable-tmp
            - mountPath: /etc/docker-credentials
              name: docker-credentials
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{ if .Values.config.useServiceAccountKey }}
        - name: google-service-account
          secret:
            secretName: {{ .Release.Name }}-google-sa-key
        {{ end }}
        - name: writable-tmp
          emptyDir: { }
        - name: config-volume
          configMap:
            name: {{ include "slsa-verde.fullname" . }}
        - name: slsa-verde-config
          secret:
            secretName: {{ include "slsa-verde.fullname" . }}
            optional: true
        - name: docker-credentials
          secret:
            defaultMode: 420
            items:
              - key: .dockerconfigjson
                path: config.json
            optional: true
            secretName: slsa-verde-docker-credentials
