apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "slsa-verde.fullname" . }}-docker-credentials
stringData:
  ".dockerconfigjson": {{ .Values.dockerconfigjson | quote }}
---
{{ if .Values.config.useServiceAccountKey }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-google-sa-key
data:
  key.json: {{ .Values.config.serviceAccountKey | b64enc | quote }}
{{ end }}