name: Build and deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'LICENSE.md'
env:
  NAME: slsa-verde
  FEATURE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais/feature

jobs:
  go_version:
    permissions:
      contents: read
    outputs:
      go_version: ${{ steps.go_version.outputs.GO_VERSION }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Find Go version
        id: go_version
        run: |
          echo "GO_VERSION=$(grep golang .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
  tests:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    needs: go_version
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # ratchet:actions/setup-go@v5
        with:
          go-version: ${{ needs.go_version.outputs.go_version }}
          cache-dependency-path: ./go.sum

      - name: Check for vulnerable dependencies
        run: make vuln

      - name: Check for deadcode
        run: make deadcode

      - name: Run tests
        run: make test

  slsa-verde:
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    needs:
      - tests
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Build push slsa-verde image
        uses: nais/platform-build-push-sign@main # ratchet:exclude
        id: build-push-sign
        with:
          name: ${{ env.NAME }}
          google_service_account: gh-${{ env.NAME }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true
          cache_from: type=gha
          cache_to: type=gha,mode=max

  orphan:
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    needs:
      - tests
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Build and push orphan image
        uses: nais/platform-build-push-sign@main # ratchet:exclude
        id: build-push-sign
        with:
          name: ${{ env.NAME }}-orphan
          dockerfile: Dockerfile.orphan
          google_service_account: gh-${{ env.NAME }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true
          cache_from: type=gha
          cache_to: type=gha,mode=max

  helm:
    outputs:
      version: ${{ steps.chart-version.outputs.version }}
    needs:
      - slsa-verde
      - orphan
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Update values.yaml
        run: |-
          yq e '.image.tag = "${{ needs.slsa-verde.outputs.version }}"' -i ./charts/values.yaml
          yq e '.orphan.image.tag = "${{ needs.orphan.outputs.version }}"' -i ./charts/values.yaml

      - uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # ratchet:azure/setup-helm@v4
        name: "Setup Helm"
        with:
          version: "v3.17.0"

      - name: Build Chart
        run: |-
          yq e '.version = "${{ needs.slsa-verde.outputs.version }}"' -i charts/Chart.yaml
          helm package charts

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935" # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "gh-${{ env.NAME }}@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"
      - name: "Login to registry"
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # ratchet:docker/login-action@v3
        with:
          registry: "europe-north1-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Push Chart
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.FEATURE_REPOSITORY }}

      - name: Chart version
        id: chart-version
        run: echo version=${{ needs.slsa-verde.outputs.version }} >> $GITHUB_OUTPUT

  rollout:
    needs:
      - helm
    runs-on: fasit-deploy
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@v2 # ratchet:exclude
        with:
          chart: ${{ env.FEATURE_REPOSITORY }}/${{ env.NAME }}
          version: ${{ needs.helm.outputs.version }}
